name = "Pumpkin's Common Base Pack"
author = "PumpkinXD"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0d2298211ac4b4fc3fab148f898c9059530ffdc831482d52a32a53ac25d32a8"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = []
