name = "Pumpkin's Common Base Pack"
author = "PumpkinXD"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ef4c74af36cadeb0a1e8bff4f0b7bc7d8c034d4a65c109a435a833bbb32e2c2"

[versions]
fabric = "0.19.5"
minecraft = "26.3"

[options]
acceptable-game-versions = []
