name = "Pumpkin's Common Base Pack"
author = "PumpkinXD"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7523627eeb67e8259aed8168215c04a4f174f3cbab08033a0f0c534a3cb8060a"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = []
